### ISSUE TITLE
Doesn't work with Pgsql Database

### ISSUE THREAD

**Issue by BnitoBzh** [juriansluiman/SlmQueueDoctrine#72] opened 2014-09-05 08:46 UTC
When adding job to queue with $queue->push($job);
There is an SQL exception : 
SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "id" violates not-null constraint

**Comment by Gounlaf** [comment] 2015-01-26 14:12
Hi,

Just to say that the problem is still pending (postgres version 9.4.0) and it will not changed : you have to get the sequence yourself, it doesn't accept "null" like for mysql ;

Using Manager is better ; but it's related to entities or document ; maybe you should have a SlmQueueDoctrine, as a base, and a SlmQueueDoctrineORM and SlmQueueDoctrineODM (like for doctrine's modules) ?

For solving the problem, I will do like @BnitoBzh ; getting next "id" can be difficult depending on platform =/

**Comment by xero88** [comment] 2015-10-02 08:30
Is there a clean solution ?

**Comment by Moring** [comment] 2015-10-02 13:03
No.  The code would have to be refactored to use the doctrine way.  Currently it uses raw sql, bypassing a lot of Doctrine goodness, which also makes it DB platform specific.  We used Gearman instead, getting the benefits of a queue and of parallel processing--it wound up being a better solution for us.

**Comment by BnitoBzh** [comment] 2015-10-02 13:14
My solution is clean, you can make the same.

**Comment by vixriihi** [comment] 2015-10-13 15:43
I used an oracle trigger & sequence to get around this issue. I think based on [this line](https://github.com/juriansluiman/SlmQueueDoctrine/blob/master/src/SlmQueueDoctrine/Queue/DoctrineQueue.php#L89) you should name the sequence <table>_id_seq and then populate id with trigger on every insert using that sequence.

**Comment by malinink** [comment] 2015-10-27 10:48
I found one solution for Postgresql, we should add default nextval() to id field.
In case of Doctrine Entity it will be:
```php
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
```

Main difference is `@ORM\GeneratedValue(strategy="IDENTITY")`

If table and sequence already exists you should to drop sequence first

**Comment by juriansluiman** [comment] 2015-11-03 19:41
For all others, @malinink proposed an alternative which seems a nice solution and works for both mysql and postgresql. Can some others test that solution? I am personally not using the SlmQueueDoctrine adapters, so anyone with a full working setup can easier test the solution. If positive, I'll merge that PR and close this one.

**Comment by malinink** [comment] 2016-03-31 14:36
@juriansluiman 

With that post I confirm that it also work fine on both mysql and postgresql databases

**mysql**
```
CREATE TABLE queue_default (id INT AUTO_INCREMENT NOT NULL, ..., 
INDEX queue_default_idx (id, status), PRIMARY KEY(id)) ...;
```
**postgresql**
```
CREATE TABLE queue_default (id SERIAL NOT NULL, ..., PRIMARY KEY(id));
CREATE INDEX queue_default_idx ON queue_default (id, status);
```

So PR #99 could be merged

**Closed** 2018-01-31 14:30 UTC
